# Generated by Django 3.2.7 on 2021-09-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('lon', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
